"""replaced server default CURRENT_TIMESTAMP with func.now() to created_at for message

Revision ID: 8d83bfbfb05c
Revises: e5376fdd6708
Create Date: 2026-04-04 17:28:00.434754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d83bfbfb05c'
down_revision: Union[str, Sequence[str], None] = 'e5376fdd6708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
