"""server_default TIMESTAMP for message

Revision ID: a4977dfbf47c
Revises: 8d83bfbfb05c
Create Date: 2026-04-04 17:35:34.248043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4977dfbf47c'
down_revision: Union[str, Sequence[str], None] = '8d83bfbfb05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
