"""add github_backend and github_frontend columns, drop github

Revision ID: d5dbbd4911cb
Revises: 77585a4f09c5
Create Date: 2026-04-16 20:07:03.861007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dbbd4911cb'
down_revision: Union[str, Sequence[str], None] = '77585a4f09c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('title', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('image', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_backend', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_frontend', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('live_at', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('technologies', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=True))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'technologies')
    op.drop_column('projects', 'live_at')
    op.drop_column('projects', 'github_frontend')
    op.drop_column('projects', 'github_backend')
    op.drop_column('projects', 'image')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'title')
    op.drop_column('projects', 'id')
    # ### end Alembic commands ###
